rules: 
  # List of contexts (i.e. apps) and their corresponding statuses
  - when:
    # Allowed statuses are:
    #
    #   - success
    #   - failure
    #   - pending
    #   - error
    continuous-integration/travis-ci/pr: success
    wip: success

    # The label to add
    label: Review Me

    # The labels to remove
    remove:
      - Waiting for something
