form:
  # All keys - except "meta" - will be considered as fields. There is only one
  # Type of fields; Text boxes. Text boxes support GFM.

  # A field may also has a help text (rendered as HTML placeholder).
  # Parentheses **Required**, but, will be stripped.
  Description:
  
  Steps to reproduce:
    for: bug report


  What is the expected behavior?:
    for: bug report

