meta: 
  types: 
    - Feature request
    - Bug report
  note: a text from maintainers

form:
  # Key: field name (rendered as label)
  # Value: a help text (rendered as input placeholder)
  Description: Write here
  
  # The value can also be an object
  Steps to reproduce:
    help: help text
    for: bug report

  What is the expected behavior?:
    for: bug report
