sudo: false

language: python
python:
  - "3.4"
  - "3.5"

env:
  - DATABASE_URL=postgres://postgres@localhost/humans

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database humans;' -U postgres

env:
  - TOX_ENV=py35-django110-drf34
  - TOX_ENV=py34-django110-drf34
  - TOX_ENV=py34-django19-drf33
  - TOX_ENV=py35-django18-drf33
  - TOX_ENV=py35-django18-drf32
  - TOX_ENV=py35-django18-drf34
  - TOX_ENV=py35-django18-drf31
  - TOX_ENV=py35-django19-drf33
  - TOX_ENV=py35-django19-drf34
  - TOX_ENV=py34-django18-drf34
  - TOX_ENV=py34-django19-drf34
  - TOX_ENV=py34-django18-drf32
  - TOX_ENV=py34-django18-drf33
  - TOX_ENV=py34-django18-drf31

install:
 - pip install tox
 - cd src/backend

script:
 - tox -e $TOX_ENV

notifications:
  email: false
