language: python

env:
  - TOXENV=py35-django110-drf34
  - TOXENV=py34-django110-drf34
  - TOXENV=py34-django19-drf33
  - TOXENV=py35-django18-drf33
  - TOXENV=py35-django18-drf32
  - TOXENV=py35-django18-drf34
  - TOXENV=py35-django18-drf31
  - TOXENV=py35-django19-drf33
  - TOXENV=py35-django19-drf34
  - TOXENV=py34-django18-drf34
  - TOXENV=py34-django19-drf34
  - TOXENV=py34-django18-drf32
  - TOXENV=py34-django18-drf33
  - TOXENV=py34-django18-drf31

install:
 - pip install tox

script:
 - tox -e $TOX_ENV

notifications:
  email: false
