sudo: false

language: python
python:
  - "3.4"
  - "3.5"

env:
  - DATABASE_URL=postgres://postgres@localhost/humans

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database humans;' -U postgres

install:
 - pip install tox-travis
 - cd src/backend

script:
 - tox -e $TOX_ENV

notifications:
  email: false
